---
title: "Exploratory Analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(hrbrthemes)

theme_set(theme_ipsum_rc())

source("../code/lib.R")

dataset = import_dataset("../data/pretty/dataset.csv")
missing_migrants = read_csv("../data/raw/MissingMigrants-Global-2018-11-07T14-37-40.csv")
migrants = missing_migrants %>%
  filter(is.element(`Region of Incident`, c("Sub-Saharan Africa", "Middle East")), # These regions have similar number of incidents
         `Reported Year` > 2015) # Only considered recent data
# View(dataset)
```

According to the Deaths at the Borders project, around `r NROW(dataset)` persons died between `r min(dataset$year)` and `r max(dataset$year)`.

## Identification of incidents

```{r}
dataset %>%
  count(incident_number) %>%
  filter(n > 10, !is.na(incident_number)) %>%
  ggplot(aes(x = reorder(incident_number, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most tragic incidents in the dataset", x = NULL, y = "Number of victims") +
    theme(panel.grid.major.y = element_blank()) +
    annotate("text", x = 28.5, y = 275, label = "atop(bold('Lampedusa boat tragedy'), 'There was a huge mobilization to find the victims')", parse = T) +
    geom_segment(data = data.frame(x1 = 30.5, y1 = 275, x2 = 33.5, y2 = 275),
                 aes(x = x1, y = y1, xend = x2, yend = y2), size = 1, color = "grey60")
```


```{r}
dataset %>%
  ggplot(aes(x = year, color = country)) +
    geom_line(stat = "count") +
    scale_y_sqrt() +
    labs(title = "Deaths at the borders during the years",
         x = "Year", y = "Number of victims", color = "Country")
```

```{r}
dataset %>%
  count(route) %>%
  ggplot(aes(x = reorder(route, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Deaths per route",
         x = "Route", y = "Number of victims")
```



```{r}
dataset %>%
  count(circumstances) %>%
  filter(!is.na(circumstances), n > 5) %>%
  ggplot(aes(x = reorder(circumstances, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most frequent circumstances",
         x = NULL, y = "Frequency")
```


```{r}
word_count = data.frame(count_words(dataset$details_of_incident))
word_count$word <- rownames(word_count)
word_count %>%
  rename(n = 1) %>%
  filter(!grepl(pattern = "[0-9]+", x = word)) %>%
  slice(1:50) %>%
  ggplot(aes(x = 1, y = 1, size = n, label = word)) +
    geom_text_repel(segment.size = 0, force = 100) +
    scale_size(range = c(2, 10), guide = FALSE) +
    scale_y_continuous(breaks = NULL) +
    scale_x_continuous(breaks = NULL) +
    labs(x = '', y = '')
```


```{r}
dataset %>%
  count(nationality) %>%
  filter(!is.na(nationality), n > 5) %>%
  ggplot(aes(x = reorder(nationality, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most frequent nationalities",
         x = NULL, y = "Frequency")
```


```{r}
dataset %>%
  count(descriptions_of_race) %>%
  filter(!is.na(descriptions_of_race)) %>%
  ggplot(aes(x = reorder(descriptions_of_race, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most frequent descriptions of race",
         x = NULL, y = "Frequency")
```

```{r}
dataset %>%
  count(sex) %>%
  filter(!is.na(sex)) %>%
  ggplot(aes(x = reorder(sex, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most frequent sex",
         x = NULL, y = "Frequency")
```

```{r}
dataset %>%
  filter(!is.na(age)) %>%
  ggplot(aes(x = age)) +
    geom_histogram() +
    labs(title = "Ages of victims",
         x = "Age", y = "Frequency")
```

# Missing migrants

```{r}
missing_migrants %>%
  group_by(`UNSD Geographical Grouping`) %>%
  summarise(n = sum(`Number Dead`)) %>%
  ggplot(aes(x = `UNSD Geographical Grouping`, y = n)) +
    geom_bar(stat = "identity") + coord_flip()
```

```{r}
missing_migrants %>%
  count(`Region of Incident`) %>%
  filter(!is.na(`Region of Incident`)) %>%
  ggplot(aes(x = reorder(`Region of Incident`, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most frequent regions",
         x = NULL, y = "Frequency")
```

```{r}


missing_migrants %>%
  # group_by(`Region of Incident`, `Reported Year`) %>%
  # summarise(`Number Dead` = median(`Number Dead`)) %>%
  ggplot(aes(x = `Reported Year`, y = `Number Dead`, color = `Region of Incident`)) +
  geom_jitter() + scale_y_sqrt() + facet_wrap(~`Region of Incident`)
```

